# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=26.2
loader_version=0.19.3
loom_version=1.17-SNAPSHOT

# Mod Properties
mod_version=1.0.2
maven_group=thatcuteone.cutiessimsplezoom
archives_base_name=cuties-simple-zoom

# Dependencies
fabric_version=0.157.0+26.2
modmenu_version=20.0.1
cloth_config_version=26.2.155